export const STORAGE_KEY = "final-frontier-save-v2";

export const WORLD = {
  radius: 600000,
  atmosphere: 70000,
  mu: 3.5316e12,
  g0: 9.80665,
  surfaceRotation: 72,
  moonRoadAltitude: 1250000,
};

export const TIERS = [
  {
    id: 0,
    key: "water",
    xp: 0,
    name: "Water Pressure",
    label: "Backyard",
    goal: "Reach 150 m with water pressure parts. There is no active steering yet, so stability matters.",
    story: "A child, a bottle, a hose, and a very serious notebook.",
  },
  {
    id: 1,
    key: "student",
    xp: 150,
    name: "Student Rockets",
    label: "School Field",
    goal: "Cross 5 km and recover safely with a parachute. Fins can now steer a little.",
    story: "Science club days: aluminum tubes, solid motors, and teachers pretending not to worry.",
  },
  {
    id: 2,
    key: "startup",
    xp: 460,
    name: "Startup Rocket",
    label: "Garage Pad",
    goal: "Reach space above 70 km. Liquid engines and decouplers make staging useful.",
    story: "A tiny company, a rented warehouse, and engines named by sleep deprived interns.",
  },
  {
    id: 3,
    key: "newspace",
    xp: 1120,
    name: "New Space",
    label: "Orbital Complex",
    goal: "Put any craft in a stable orbit: periapsis and apoapsis both above 70 km.",
    story: "Reusable dreams, clean telemetry, and a launch pad that finally looks insured.",
  },
  {
    id: 4,
    key: "nasa",
    xp: 1800,
    name: "Nasa",
    label: "Deep Space Center",
    goal: "Send a crewed rocket onto a road to the Moon with an apoapsis above 1,250 km.",
    story: "The little company has grown up, but someone still keeps the first bottle on a shelf.",
  },
];

export const PARTS = [
  {
    id: "paper-cone",
    tier: 0,
    category: "Nose",
    name: "Paper Cone",
    short: "Soft nose",
    dryMass: 0.04,
    width: 0.55,
    height: 0.55,
    drag: 0.52,
    color: "#ef6f6c",
    shape: "cone",
  },
  {
    id: "water-bottle",
    tier: 0,
    category: "Tanks",
    name: "Water Bottle",
    short: "0.7 kg water",
    dryMass: 0.12,
    fuelMass: 0.7,
    fuelType: "water",
    width: 0.62,
    height: 1.35,
    drag: 0.72,
    color: "#86d4f7",
    shape: "bottle",
  },
  {
    id: "cork-nozzle",
    tier: 0,
    category: "Engines",
    name: "Cork Nozzle",
    short: "85 N",
    dryMass: 0.05,
    width: 0.48,
    height: 0.36,
    drag: 0.85,
    color: "#b87b4b",
    shape: "engine",
    engine: { fuelType: "water", thrust: 85, ispSea: 18, ispVac: 24, throttle: false },
  },
  {
    id: "wood-fins",
    tier: 0,
    category: "Control",
    name: "Wood Fins",
    short: "stable",
    dryMass: 0.08,
    width: 0.9,
    height: 0.3,
    drag: 0.9,
    stability: 0.45,
    color: "#d8aa63",
    shape: "fins",
  },
  {
    id: "student-cone",
    tier: 1,
    category: "Nose",
    name: "Balsa Nose",
    short: "cleaner",
    dryMass: 0.28,
    width: 0.62,
    height: 0.68,
    drag: 0.38,
    color: "#f68f65",
    shape: "cone",
  },
  {
    id: "aluminum-body",
    tier: 1,
    category: "Bodies",
    name: "Aluminum Body",
    short: "sturdy shell",
    dryMass: 1.35,
    width: 0.68,
    height: 1.15,
    drag: 0.48,
    color: "#c9d0d6",
    shape: "tube",
  },
  {
    id: "powder-booster",
    tier: 1,
    category: "Engines",
    name: "Solid Booster",
    short: "1.6 kN",
    dryMass: 1.1,
    fuelMass: 3.6,
    fuelType: "solid",
    width: 0.66,
    height: 1.15,
    drag: 0.55,
    color: "#d95f56",
    shape: "booster",
    engine: { fuelType: "solid", thrust: 1600, ispSea: 92, ispVac: 108, throttle: false },
  },
  {
    id: "student-chute",
    tier: 1,
    category: "Recovery",
    name: "Parachute",
    short: "safe landing",
    dryMass: 0.34,
    width: 0.62,
    height: 0.38,
    drag: 0.6,
    parachute: { area: 18, safeSpeed: 105 },
    color: "#f3c15f",
    shape: "chute",
  },
  {
    id: "servo-fins",
    tier: 1,
    category: "Control",
    name: "Controlled Flaps",
    short: "steerable",
    dryMass: 0.62,
    width: 1.0,
    height: 0.34,
    drag: 0.82,
    control: 0.42,
    stability: 0.55,
    color: "#75b979",
    shape: "fins",
  },
  {
    id: "avionics-core",
    tier: 2,
    category: "Command",
    name: "Avionics Core",
    short: "SAS",
    dryMass: 1.2,
    width: 0.74,
    height: 0.54,
    drag: 0.44,
    command: true,
    control: 0.72,
    color: "#6f86c9",
    shape: "box",
  },
  {
    id: "small-liquid-tank",
    tier: 2,
    category: "Tanks",
    name: "Small Fuel Tank",
    short: "20 kg fuel",
    dryMass: 2.4,
    fuelMass: 20,
    fuelType: "liquid",
    width: 0.76,
    height: 1.25,
    drag: 0.44,
    color: "#f3d36e",
    shape: "tank",
  },
  {
    id: "puddlehopper",
    tier: 2,
    category: "Engines",
    name: "Puddlehopper Engine",
    short: "11 kN",
    dryMass: 4.2,
    width: 0.74,
    height: 0.62,
    drag: 0.56,
    color: "#4b6f91",
    shape: "engine",
    engine: { fuelType: "liquid", thrust: 11000, ispSea: 218, ispVac: 295, throttle: true },
  },
  {
    id: "light-decoupler",
    tier: 2,
    category: "Staging",
    name: "Light Decoupler",
    short: "stage split",
    dryMass: 0.85,
    width: 0.82,
    height: 0.26,
    drag: 0.5,
    decoupler: true,
    color: "#9aa6b6",
    shape: "ring",
  },
  {
    id: "steering-fins",
    tier: 2,
    category: "Control",
    name: "Steering Fins",
    short: "strong turn",
    dryMass: 0.95,
    width: 1.1,
    height: 0.38,
    drag: 0.76,
    control: 0.62,
    stability: 0.75,
    color: "#5bbf9c",
    shape: "fins",
  },
  {
    id: "probe-core",
    tier: 3,
    category: "Command",
    name: "Probe Core",
    short: "orbital SAS",
    dryMass: 2.4,
    width: 0.92,
    height: 0.52,
    drag: 0.36,
    command: true,
    control: 1.1,
    color: "#5c6fae",
    shape: "box",
  },
  {
    id: "orbital-tank",
    tier: 3,
    category: "Tanks",
    name: "Orbital Tank",
    short: "80 kg fuel",
    dryMass: 8,
    fuelMass: 80,
    fuelType: "liquid",
    width: 1.0,
    height: 1.62,
    drag: 0.36,
    color: "#f0c857",
    shape: "tank",
  },
  {
    id: "booster-tank",
    tier: 3,
    category: "Tanks",
    name: "Booster Tank",
    short: "165 kg fuel",
    dryMass: 15,
    fuelMass: 165,
    fuelType: "liquid",
    width: 1.18,
    height: 1.82,
    drag: 0.41,
    color: "#e8b64e",
    shape: "tank",
  },
  {
    id: "mainstay-engine",
    tier: 3,
    category: "Engines",
    name: "Mainstay Engine",
    short: "90 kN",
    dryMass: 12,
    width: 1.06,
    height: 0.82,
    drag: 0.52,
    color: "#40566f",
    shape: "engine",
    engine: { fuelType: "liquid", thrust: 90000, ispSea: 255, ispVac: 315, throttle: true },
  },
  {
    id: "vacuum-engine",
    tier: 3,
    category: "Engines",
    name: "Vacuum Engine",
    short: "24 kN",
    dryMass: 7,
    width: 0.88,
    height: 0.82,
    drag: 0.6,
    color: "#53718f",
    shape: "engine",
    engine: { fuelType: "liquid", thrust: 24000, ispSea: 120, ispVac: 348, throttle: true },
  },
  {
    id: "orbital-decoupler",
    tier: 3,
    category: "Staging",
    name: "Stack Decoupler",
    short: "reliable",
    dryMass: 1.4,
    width: 1.04,
    height: 0.32,
    drag: 0.42,
    decoupler: true,
    color: "#8b98aa",
    shape: "ring",
  },
  {
    id: "solar-wing",
    tier: 3,
    category: "Utility",
    name: "Solar Wings",
    short: "deep power",
    dryMass: 1.3,
    width: 1.35,
    height: 0.42,
    drag: 0.65,
    control: 0.12,
    color: "#5fb7dc",
    shape: "wings",
  },
  {
    id: "crew-capsule",
    tier: 4,
    category: "Command",
    name: "Crew Capsule",
    short: "habited",
    dryMass: 7.5,
    width: 1.18,
    height: 0.9,
    drag: 0.33,
    command: true,
    crew: true,
    control: 1.35,
    parachute: { area: 28, safeSpeed: 145 },
    color: "#e7eef4",
    shape: "capsule",
  },
  {
    id: "service-module",
    tier: 4,
    category: "Utility",
    name: "Service Module",
    short: "110 kg fuel",
    dryMass: 10,
    fuelMass: 110,
    fuelType: "liquid",
    width: 1.12,
    height: 1.18,
    drag: 0.38,
    command: true,
    control: 0.9,
    color: "#b8c6d6",
    shape: "tube",
  },
  {
    id: "heavy-tank",
    tier: 4,
    category: "Tanks",
    name: "Heavy Fuel Tank",
    short: "430 kg fuel",
    dryMass: 36,
    fuelMass: 430,
    fuelType: "liquid",
    width: 1.42,
    height: 2.2,
    drag: 0.44,
    color: "#d9b14e",
    shape: "tank",
  },
  {
    id: "atlas-engine",
    tier: 4,
    category: "Engines",
    name: "Atlas Cluster",
    short: "310 kN",
    dryMass: 34,
    width: 1.42,
    height: 1.0,
    drag: 0.56,
    color: "#344c62",
    shape: "engine",
    engine: { fuelType: "liquid", thrust: 310000, ispSea: 262, ispVac: 334, throttle: true },
  },
  {
    id: "lunar-engine",
    tier: 4,
    category: "Engines",
    name: "Lunar Engine",
    short: "38 kN",
    dryMass: 9,
    width: 0.94,
    height: 0.92,
    drag: 0.58,
    color: "#4f657a",
    shape: "engine",
    engine: { fuelType: "liquid", thrust: 38000, ispSea: 88, ispVac: 365, throttle: true },
  },
  {
    id: "heavy-decoupler",
    tier: 4,
    category: "Staging",
    name: "Heavy Decoupler",
    short: "large stack",
    dryMass: 2.8,
    width: 1.42,
    height: 0.36,
    drag: 0.44,
    decoupler: true,
    color: "#7f8fa2",
    shape: "ring",
  },
  {
    id: "landing-legs",
    tier: 4,
    category: "Recovery",
    name: "Landing Legs",
    short: "gentle touch",
    dryMass: 3.1,
    width: 1.5,
    height: 0.42,
    drag: 0.7,
    stability: 0.28,
    color: "#6d7a86",
    shape: "legs",
  },
];

export const MILESTONES = [
  { id: "first-hop", label: "First hop", xp: 35, test: f => f.maxAltitude >= 60 },
  { id: "backyard-150", label: "Backyard record", xp: 60, test: f => f.maxAltitude >= 150 },
  { id: "student-1k", label: "One kilometer", xp: 90, test: f => f.maxAltitude >= 1000 },
  { id: "student-5k", label: "Upper school sky", xp: 140, test: f => f.maxAltitude >= 5000 },
  { id: "safe-recovery", label: "Recovered craft", xp: 95, test: f => f.landed && f.landingSpeed < 16 },
  { id: "supersonic", label: "Mach-ish club", xp: 120, test: f => f.maxSpeed >= 330 },
  { id: "space", label: "Reached space", xp: 260, test: f => f.maxAltitude >= WORLD.atmosphere },
  { id: "orbit", label: "First stable orbit", xp: 620, test: f => f.orbitAchieved },
  { id: "crew-orbit", label: "People in orbit", xp: 420, test: f => f.orbitAchieved && f.hadCrew },
  { id: "moon-road", label: "Road to the Moon", xp: 900, test: f => f.moonRoad && f.hadCrew },
];

export function getPart(id) {
  return PARTS.find(part => part.id === id);
}

export function tierForXp(xp) {
  let tier = TIERS[0];
  for (const candidate of TIERS) {
    if (xp >= candidate.xp) tier = candidate;
  }
  return tier;
}

export function nextTierForXp(xp) {
  return TIERS.find(tier => tier.xp > xp) || null;
}
