// Generated from the Morentia workbook. Edit through the in-app card studio or regenerate.
export const CATALOG = {
  "meta": {
    "name": "Morentia",
    "source": "Morentia_cartes_equilibrees_test_physique_v1.xlsx",
    "schemaVersion": 1,
    "generatedAt": "2026-07-31"
  },
  "rules": [
    {
      "title": "Portée du classeur",
      "text": "Version de test physique équilibrée à partir de « Jeu de carte (1).pdf » et des décisions prises dans la conversation. Les coûts restent à valider par le test : ce fichier fixe une première version cohérente, pas un équilibre mathématiquement prouvé."
    },
    {
      "title": "Jour",
      "text": "Un Jour correspond à un round complet, de l’Aube jusqu’à la fin de la Nuit. À chaque nouvelle Aube, chaque joueur pioche une carte et les effets « une fois par Jour » redeviennent disponibles."
    },
    {
      "title": "Influence",
      "text": "Lorsqu’un effet fait gagner ou perdre de l’influence sans indiquer de durée, la modification est permanente. Un bonus conditionnel cesse dès que sa condition n’est plus remplie."
    },
    {
      "title": "Or",
      "text": "L’or gagné pendant la Journée, le Crépuscule, la Guerre ou la Nuit rejoint la réserve, sauf si le texte précise « or actif ». À l’Aube, la réserve rejoint l’or actif avant les autres effets d’Aube."
    },
    {
      "title": "Détruire / défausser",
      "text": "Une carte détruite rejoint la défausse et déclenche les effets liés à la destruction. Une carte simplement défaussée ne déclenche pas ces effets. Lorsqu’un lieu expire, chaque joueur choisit ses Survivantes : elles retournent dans son domaine et ses autres cartes sont défaussées."
    },
    {
      "title": "Activer un effet",
      "text": "Activer un effet précédé de « Action — » coûte une action. Les effets déclenchés et les effets d’Aube/Crépuscule/Nuit ne coûtent pas d’action."
    },
    {
      "title": "Rejoindre un lieu",
      "text": "Une carte rejoint un lieu lorsqu’elle y entre depuis la main, le marché, le domaine ou un autre lieu."
    },
    {
      "title": "Changer de lieu",
      "text": "Changer directement de lieu signifie passer d’un lieu à un autre sans transiter par le domaine."
    },
    {
      "title": "Contrôle",
      "text": "Le joueur avec strictement le plus d’influence totale contrôle le lieu. En cas d’égalité, personne ne le contrôle."
    },
    {
      "title": "Guerre",
      "text": "Comparez l’influence dans les domaines. Les gagnants gagnent 1 or dans leur réserve ; les perdants perdent 1 or actif si possible. En cas de plusieurs gagnants, un perdant ne perd qu’un seul or."
    },
    {
      "title": "Monstres",
      "text": "Les Lieux — Monstre sans Durée restent en jeu jusqu’à ce que leur Seuil soit atteint. Le Seuil est vérifié à la Nuit. Lorsqu’il est atteint, le monstre est vaincu et le lieu expire."
    },
    {
      "title": "Mise en place conseillée",
      "text": "Main de départ : 4 cartes ; or actif : 3 ; un mulligan gratuit. Marché : 3 cartes. Lieux actifs : 2. Une carte jouée dans le domaine arrive épuisée jusqu’à la prochaine Aube. Fin de partie après 2 × nombre de joueurs + 2 lieux expirés."
    },
    {
      "title": "Copies",
      "text": "Chaque faction utilise un deck fixe de 25 cartes. Les cartes indiquées en 2 exemplaires servent de noyau régulier ; les moteurs, finisseurs et cartes complexes restent en un exemplaire."
    }
  ],
  "factions": {
    "Kalassir": [
      {
        "faction": "Kalassir",
        "id": "KAL-BASE",
        "name": "Kalassir, Cité du Premier Sang",
        "status": "Base",
        "type": "Base",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "À l’Aube, gagnez 2 ors actifs.\nLa première fois chaque Jour qu’une carte alliée rejoint votre défausse, gagnez 1 or dans votre réserve.",
        "role": "Économie et sacrifice",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Déclenchement limité à une fois par Jour.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-POUVOIR",
        "name": "Conseil des Trois Ordres",
        "status": "Pouvoir",
        "type": "Pouvoir de faction",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "Un seul Ordre est actif à la fois. À l’Aube, vous pouvez payer 1 or actif pour changer d’Ordre.\nLames de Karina — La première carte alliée qui rejoint un lieu contrôlé par un adversaire chaque Jour gagne +2 influence jusqu’à l’Aube.\nCulte du Premier Sang — Vos cartes dans votre domaine gagnent +1 influence.\nDisciples de Karlov — La première fois chaque Jour qu’une carte alliée présente sur un lieu que vous contrôlez devrait être détruite, remettez-la dans votre main à la place.",
        "role": "Choix de posture",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "Formulation unifiée ; remplacement de destruction explicite.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-01",
        "name": "Inquisiteur du Sang Noir",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 5,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint un lieu, détruisez une autre carte présente sur ce lieu ayant 1 influence ou moins.",
        "role": "Interaction / exécution",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Coût conservé ; cible « autre » précisée.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-02",
        "name": "Archive de Chair",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 2,
        "domainCost": 4,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Une fois par Jour, lorsqu’une carte alliée rejoint votre défausse, regardez la première carte de votre deck. Vous pouvez la laisser au-dessus du deck ou la placer sous votre deck.",
        "role": "Filtrage",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "« Garder » remplacé par « laisser au-dessus » ; ne fait plus piocher.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-03",
        "name": "Saint du Sang Pur",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 3,
        "domainCost": 5,
        "locationCost": 7,
        "uniqueCost": null,
        "quantity": 1,
        "text": "La première fois chaque Jour qu’une autre carte est détruite sur ce lieu, cette carte gagne +1 influence.",
        "role": "Finisseur croissant",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Gain limité à une fois par Jour ; coût conservé à 5/7.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-04",
        "name": "Malédiction Sanguine",
        "status": "Deck",
        "type": "Attachement d’unité",
        "subtype": "Malédiction",
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 4,
        "quantity": 1,
        "text": "Attachez cette carte à une unité présente sur un lieu.\nLes autres unités contrôlées par le contrôleur de la carte attachée présentes sur ce lieu ont -1 influence.",
        "role": "Affaiblissement de groupe",
        "complexity": "Moyenne",
        "risk": "Moyen",
        "adjustment": "Devient un véritable Attachement ; bénéficiaire du malus précisé.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-05",
        "name": "Rituel de Transfusion",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 3,
        "quantity": 1,
        "text": "Détruisez une carte alliée présente sur un lieu. Une autre carte alliée présente sur ce même lieu gagne +3 influence.",
        "role": "Sacrifice / transfert",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Les deux cartes doivent être sur le même lieu ; gain permanent.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-06",
        "name": "Exécuteur de Karina",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 3,
        "domainCost": 4,
        "locationCost": 5,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint un lieu contrôlé par un adversaire, vous pouvez détruire une de vos autres cartes présentes sur ce lieu. Si vous le faites, cette carte gagne +3 influence.",
        "role": "Prise de contrôle agressive",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Coût de domaine augmenté de 3 à 4.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-07",
        "name": "Fanatique du Premier Sang",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Lorsque cette carte est détruite, une autre carte alliée présente sur ce lieu gagne +2 influence.",
        "role": "Sacrifice rentable",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Conservée comme carte de noyau en 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-08",
        "name": "Laboratoire d’Hématologie",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "À l’Aube, vous pouvez défausser une carte alliée de votre domaine. Si vous le faites, piochez une carte ou gagnez 1 or dans votre réserve.",
        "role": "Conversion de ressources",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Défausse et non destruction maintenue.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-09",
        "name": "Héritier du Sang",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 5,
        "uniqueCost": null,
        "quantity": 1,
        "text": "À l’Aube, choisissez une unité alliée dans votre défausse. Cette carte gagne les effets imprimés de l’unité choisie jusqu’à la prochaine Aube. Elle ne copie ni son nom, ni son influence, ni ses types, ni ses coûts.",
        "role": "Copie contextuelle",
        "complexity": "Élevée",
        "risk": "Élevé",
        "adjustment": "Portée de la copie explicitée.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-10",
        "name": "Croisade du Premier Sang",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 2,
        "domainCost": 4,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "La première fois chaque Jour que vous prenez le contrôle d’un lieu à un adversaire, gagnez 1 or dans votre réserve et une carte alliée présente sur ce lieu gagne +1 influence.",
        "role": "Récompense de conquête",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Limite journalière conservée.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-11",
        "name": "Récolte Sanguine",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 2,
        "domainCost": 4,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque vous remportez la Guerre, vous pouvez piocher une carte au lieu de gagner l’or accordé par la Guerre.",
        "role": "Avantage de cartes",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Interaction avec la règle de Guerre précisée.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-12",
        "name": "Converti Fanatique",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 2,
        "text": "La première fois chaque Jour que vous changez d’Ordre actif, cette carte gagne +1 influence.",
        "role": "Croissance par changement d’Ordre",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Limité à une fois par Jour ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-13",
        "name": "Héraut de Karina",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Tant que les Lames de Karina sont l’Ordre actif, cette carte gagne +2 influence.",
        "role": "Unité de posture",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Bonus conditionnel non permanent ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-14",
        "name": "Archiviste de Karlov",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Tant que les Disciples de Karlov sont l’Ordre actif, la première fois chaque Jour qu’une carte alliée est détruite, piochez une carte.",
        "role": "Moteur de pioche",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Limite journalière explicite.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-15",
        "name": "Salle d’Opération",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "À l’Aube, vous pouvez retirer 1 influence à une carte alliée. Si vous le faites, une autre carte alliée gagne +2 influence jusqu’à la prochaine Aube.",
        "role": "Transfert temporaire",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Durée explicite pour éviter une croissance infinie.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-16",
        "name": "Médecin des Apôtres",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint votre domaine, vous pouvez remettre dans votre main une carte alliée de votre défausse.",
        "role": "Récupération",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Récupération de n’importe quelle carte conservée ; un seul exemplaire.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-17",
        "name": "Héritier des Martyrs",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": "*",
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Cette carte possède une influence égale à 1 plus le nombre d’unités alliées dans votre défausse, avec un maximum de 5.",
        "role": "Payoff de défausse",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Nouvelle formule lisible et plafonnée.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-18",
        "name": "Dîme du Premier Sang",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 1,
        "quantity": 1,
        "text": "Défaussez une unité de votre main. Gagnez dans votre réserve un nombre d’ors égal à son influence imprimée, avec un maximum de 3.",
        "role": "Accélération économique",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Plafond à 3 pour éviter les explosions d’or.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-19",
        "name": "Apôtre du Premier Sang",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Tant que le Culte du Premier Sang est l’Ordre actif, après la Guerre, si vous n’êtes pas parmi les perdants, une carte alliée dans votre domaine gagne +1 influence.",
        "role": "Croissance militaire",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "Résultat de Guerre clarifié ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      },
      {
        "faction": "Kalassir",
        "id": "KAL-20",
        "name": "Messager du Conseil",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Lorsque cette carte rejoint votre domaine, vous pouvez changer d’Ordre actif sans payer le coût du Conseil des Trois Ordres.",
        "role": "Flexibilité de posture",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Interaction avec le pouvoir précisée ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/kalassir.jpg"
      }
    ],
    "Aqaba": [
      {
        "faction": "Aqaba",
        "id": "AQA-BASE",
        "name": "Aqaba, Cité des Mille Échanges",
        "status": "Base",
        "type": "Base",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "À l’Aube, gagnez 2 ors actifs.\nLa première fois chaque Jour que vous achetez une carte du marché, gagnez 1 or dans votre réserve.",
        "role": "Économie de marché",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Déclenchement limité à une fois par Jour.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-POUVOIR",
        "name": "Enfants des Astres",
        "status": "Pouvoir",
        "type": "Pouvoir de faction",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "À l’Aube, regardez la première carte du deck de lieux. Vous pouvez la laisser au-dessus du deck ou la placer sous le deck.",
        "role": "Anticipation",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Référence aux événements retirée pour l’alpha.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-01",
        "name": "Marchand de Caravane",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 1,
        "locationCost": 2,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Lorsque cette carte est jouée, vous pouvez payer X ors. Elle gagne +X influence. X ne peut pas dépasser 3.",
        "role": "Dépense d’or / scaling",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Plafond à 3 ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-02",
        "name": "Grande Caravane",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Action — Une fois par Jour, vous pouvez payer 1 or. Une carte alliée gagne +1 influence jusqu’à la prochaine Aube.",
        "role": "Soutien flexible",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Une fois par Jour et activation en action.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-03",
        "name": "Acheteur Compulsif",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte est jouée, vous pouvez payer 2 ors. Si vous le faites, révélez la première carte du deck de marché. Si elle peut être légalement jouée, jouez-la immédiatement gratuitement, dans une zone légale de votre choix, sans dépenser d’action supplémentaire. Sinon, placez-la sous le deck de marché.",
        "role": "Gamble / accélération",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "La carte révélée est réellement gratuite ; le risque vient du dessus inconnu et des cartes injouables.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-04",
        "name": "Singe du Marché",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 1,
        "locationCost": 2,
        "uniqueCost": null,
        "quantity": 2,
        "text": "La première fois chaque Jour que cette carte fait perdre le contrôle d’un lieu à un adversaire, prenez-lui 1 or actif et placez-le dans votre réserve. S’il n’a pas d’or actif, rien ne se passe.",
        "role": "Vol opportuniste",
        "complexity": "Moyenne",
        "risk": "Moyen",
        "adjustment": "Déclenchement limité ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-05",
        "name": "Éclaireur du Désert",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint un lieu, regardez la première carte du deck de marché. Vous pouvez la laisser au-dessus du deck ou la placer sous le deck.",
        "role": "Préparation du Gamble",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Choix dessus/dessous ajouté.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-06",
        "name": "Grand Philosophe d’Aqaba",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 4,
        "locationCost": 6,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Les cartes adverses ayant 5 influence ou plus ont -2 influence sur ce lieu.",
        "role": "Contre aux grandes unités",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Ancien effet 5+ → 1 remplacé par -2, moins polarisant contre les Géants.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-07",
        "name": "Maître Esclavagiste",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 4,
        "domainCost": 5,
        "locationCost": 7,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque le lieu sur lequel cette carte est présente expire, si vous le contrôlez, choisissez une unité adverse présente sur ce lieu ayant 3 influence imprimée ou moins. Au lieu de la détruire, placez-la dans votre domaine, épuisée, sous votre contrôle.",
        "role": "Capture",
        "complexity": "Élevée",
        "risk": "Élevé",
        "adjustment": "Coût augmenté ; cible plafonnée à 3 influence imprimée.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-08",
        "name": "Banque Centrale",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 2,
        "domainCost": 4,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "À l’Aube, choisissez un effet jusqu’à la prochaine Aube :\n• Les cartes du marché coûtent 1 or de moins à tous les joueurs, minimum 1.\n• Les cartes du marché coûtent 1 or de plus à tous les joueurs.",
        "role": "Contrôle global du marché",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Durée et minimum précisés.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-09",
        "name": "Tempête de Sable",
        "status": "Deck",
        "type": "Attachement de lieu",
        "subtype": "Météo",
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 4,
        "quantity": 1,
        "text": "Chaque joueur ne peut jouer ou déployer qu’une seule carte sur ce lieu chaque Jour.",
        "role": "Ralentissement d’un lieu",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Devient un Attachement de lieu permanent jusqu’à expiration.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-10",
        "name": "Courtier du Bazar",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Lorsque cette carte est jouée, vous pouvez placer une carte visible du marché sous le deck de marché. Remplacez-la immédiatement.",
        "role": "Renouvellement du marché",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Destination de la carte précisée ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-11",
        "name": "Marchand Ambulant",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint votre domaine, piochez la première carte du deck de marché et ajoutez-la à votre main.",
        "role": "Avantage de cartes de marché",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Nouvelle version : la carte va dans la main et doit ensuite être payée.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-12",
        "name": "Investisseur du Désert",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "La première fois chaque Jour qu’un effet place de l’or dans votre réserve, placez-y 1 or supplémentaire.",
        "role": "Amplification économique",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Limité à une fois par Jour pour éviter les chaînes.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-13",
        "name": "Guide des Dunes",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Tant qu’au moins un Attachement de lieu est attaché à ce lieu, cette carte gagne +1 influence.",
        "role": "Synergie avec les lieux modifiés",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Condition reformulée ; bonus conservé à +1.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-14",
        "name": "Collecteur des Routes",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "La première fois chaque Jour qu’un adversaire achète une carte du marché, gagnez 1 or dans votre réserve.",
        "role": "Taxation",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "« Joue » remplacé par « achète ».",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-15",
        "name": "Herbe des Astres",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 1,
        "quantity": 1,
        "text": "Regardez les deux premières cartes de votre deck. Ajoutez-en une à votre main et placez l’autre sous votre deck.",
        "role": "Filtrage",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Texte simplifié.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-16",
        "name": "Herbe Rouge",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 2,
        "quantity": 1,
        "text": "Une carte alliée gagne +2 influence jusqu’à la prochaine Aube.",
        "role": "Boost temporaire",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Durée explicitée.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-17",
        "name": "Négociant Curieux",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 1,
        "text": "La première fois chaque Jour que vous achetez une carte du marché, piochez une carte puis défaussez une carte.",
        "role": "Filtrage après achat",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Conservée telle quelle avec vocabulaire unifié.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-18",
        "name": "Assassin des Ruelles",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint un lieu, vous pouvez payer X ors. Détruisez une carte adverse présente sur ce lieu ayant X influence ou moins. X ne peut pas dépasser 4.",
        "role": "Destruction contre or",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Plafond à 4.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-19",
        "name": "Corruption",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": "X",
        "quantity": 1,
        "text": "Choisissez une carte adverse. Elle perd X influence jusqu’à la prochaine Aube. X ne peut pas dépasser 3.",
        "role": "Contrôle de l’influence",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Durée unifiée.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-20",
        "name": "Prince Marchand",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 4,
        "locationCost": 6,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Cette carte gagne +1 influence pour chaque tranche complète de 2 ors dans votre réserve, avec un maximum de +3.",
        "role": "Payoff de réserve",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Bonus plafonné à +3.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-21",
        "name": "Mercenaire Doré",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 3,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte rejoint un lieu, vous pouvez payer 1 or. Si vous le faites, elle gagne +1 influence jusqu’à la prochaine Aube.",
        "role": "Unité efficace contre paiement",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Coûts augmentés de 2/3 à 3/4.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      },
      {
        "faction": "Aqaba",
        "id": "AQA-22",
        "name": "Chambre des Taxes",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 3,
        "domainCost": 5,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque vous remportez la Guerre, gagnez 1 or supplémentaire dans votre réserve.",
        "role": "Supériorité économique militaire",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Coût augmenté de 4 à 5.",
        "included": "Oui",
        "illustration": "assets/art/aqaba.jpg"
      }
    ],
    "Algarie": [
      {
        "faction": "Algarie",
        "id": "ALG-BASE",
        "name": "Les Plaines de l’Endormi",
        "status": "Base",
        "type": "Base",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "À l’Aube, gagnez 2 ors actifs.\nLa première fois chaque Jour que vous déployez une carte, gagnez 1 or dans votre réserve.",
        "role": "Économie de déploiement",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Déclenchement limité à une fois par Jour.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-POUVOIR",
        "name": "Le Souffle d’Aelunn",
        "status": "Pouvoir",
        "type": "Pouvoir de faction",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "Lorsqu’une carte alliée change directement de lieu sans passer par votre domaine, elle gagne +1 influence jusqu’à la prochaine Aube. Chaque carte ne peut gagner ce bonus qu’une fois par Jour.",
        "role": "Mobilité",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Chaque unité peut en profiter une fois par Jour ; empêche les boucles sur une même carte.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-01",
        "name": "Le Nocturne",
        "status": "Deck",
        "type": "Unité",
        "subtype": "Géant",
        "influence": 5,
        "domainCost": 7,
        "locationCost": 9,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Un seul Géant peut être présent sur un lieu.\nAu Crépuscule, vous pouvez déplacer une carte alliée vers ce lieu.\nLes autres effets « Au Crépuscule » des cartes présentes sur ce lieu et du lieu se déclenchent une fois supplémentaire.",
        "role": "Géant de combo",
        "complexity": "Élevée",
        "risk": "Élevé",
        "adjustment": "Le double déclenchement exclut son propre déplacement.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-02",
        "name": "Le Contrevent",
        "status": "Deck",
        "type": "Unité",
        "subtype": "Géant",
        "influence": 5,
        "domainCost": 7,
        "locationCost": 9,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Un seul Géant peut être présent sur un lieu.\nAu Crépuscule, vous pouvez déplacer une carte alliée vers ce lieu.\nÀ la Nuit, chaque joueur détruit une carte qu’il contrôle présente sur ce lieu, s’il le peut.",
        "role": "Géant de pression",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "Défausse remplacée par destruction pour cohérence avec Kalassir.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-03",
        "name": "Le Brasier Lent",
        "status": "Deck",
        "type": "Unité",
        "subtype": "Géant",
        "influence": 5,
        "domainCost": 8,
        "locationCost": 10,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Un seul Géant peut être présent sur un lieu.\nAu Crépuscule, vous pouvez déplacer une carte alliée vers ce lieu.\nAu Crépuscule, chaque carte présente sur ce lieu gagne +1 influence.",
        "role": "Géant de croissance",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Gain permanent et symétrique conservé ; coût élevé.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-04",
        "name": "Éveil de l’Endormi",
        "status": "Deck",
        "type": "Attachement de lieu",
        "subtype": "Rituel",
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 6,
        "quantity": 1,
        "text": "Attachez cette carte à un lieu non-Monstre.\nJusqu’à l’expiration de ce lieu, vos cartes présentes sur ce lieu ajoutent également leur influence à votre total pour la Guerre. Elles restent présentes sur ce lieu.",
        "role": "Transformation stratégique",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "Ancien texte « le lieu devient votre domaine » remplacé par une règle testable.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-05",
        "name": "Éclaireur des Steppes",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 1,
        "locationCost": 2,
        "uniqueCost": null,
        "quantity": 2,
        "text": "Lorsque le lieu sur lequel cette carte est présente expire, vous pouvez déplacer cette carte vers un lieu adjacent au lieu expiré au lieu de la détruire.",
        "role": "Survie mobile",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-06",
        "name": "Monture des Plaines",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 2,
        "text": "La première fois chaque Jour que cette carte change directement de lieu, vous pouvez déplacer avec elle une autre carte alliée présente sur son lieu de départ vers le même lieu d’arrivée. Ce déplacement ne déclenche pas l’effet d’une autre Monture des Plaines.",
        "role": "Déplacement de groupe",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "Limite journalière et anti-chaîne ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-07",
        "name": "Cavalier des Rafales",
        "status": "Deck",
        "type": "Unité recto-verso",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque cette carte est déployée depuis votre domaine, elle gagne +2 influence jusqu’à la prochaine Aube.\nLorsque cette carte devrait être détruite, retournez-la sur sa face Vétéran des Rafales et placez-la dans votre domaine, épuisée, à la place.",
        "role": "Unité à deux vies",
        "complexity": "Moyenne",
        "risk": "Élevé",
        "adjustment": "Transformation et destination précisées.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-07B",
        "name": "Vétéran des Rafales",
        "status": "Verso",
        "type": "Unité recto-verso",
        "subtype": null,
        "influence": 3,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 0,
        "text": "Lorsque cette carte est déployée depuis votre domaine, vous pouvez détruire une carte adverse ayant 1 influence ou moins présente sur ce lieu.",
        "role": "Deuxième forme",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Verso non compté séparément dans le deck.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-08",
        "name": "Rafale des Steppes",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 2,
        "quantity": 2,
        "text": "Déplacez une carte présente sur un lieu vers un lieu adjacent.",
        "role": "Mobilité ouverte",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-09",
        "name": "Campement Nomade",
        "status": "Deck",
        "type": "Attachement de lieu",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 3,
        "quantity": 1,
        "text": "Les cartes alliées que vous jouez directement sur ce lieu coûtent 1 or de moins, minimum 1. Cet effet ne réduit pas le coût des déploiements.",
        "role": "Réduction locale",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Différence jouer/déployer précisée.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-10",
        "name": "Passefrontière",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 2,
        "text": "La première fois chaque Jour que cette carte change directement de lieu vers un lieu adjacent, gagnez 1 or dans votre réserve.",
        "role": "Mobilité économique",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-11",
        "name": "Pisteur de Géant",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 3,
        "domainCost": 3,
        "locationCost": 5,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Cette carte coûte 0 or à jouer directement sur un lieu où un Géant est présent.",
        "role": "Soutien des Géants",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Conservée comme récompense d’un investissement lourd.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-12",
        "name": "Route des Clans",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 1,
        "domainCost": 3,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Action — Une fois par Jour, vous pouvez payer 1 or pour déplacer une carte alliée présente sur un lieu vers un lieu adjacent.",
        "role": "Moteur de mobilité",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Activation en action précisée.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-13",
        "name": "Messager des Vents",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 1,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 1,
        "text": "La première fois chaque Jour qu’une carte alliée change directement de lieu, piochez une carte puis défaussez une carte.",
        "role": "Filtrage par mobilité",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Déclenchement reformulé.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-14",
        "name": "Charge des Steppes",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 4,
        "quantity": 1,
        "text": "Déplacez une carte alliée vers un lieu adjacent. Détruisez une carte adverse présente sur le lieu d’arrivée ayant moins d’influence que la carte déplacée.",
        "role": "Mobilité offensive",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Coût augmenté de 3 à 4.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-15",
        "name": "Guerrier Nomade",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 2,
        "locationCost": 3,
        "uniqueCost": null,
        "quantity": 2,
        "text": "La première fois chaque Jour que cette carte change directement de lieu, elle gagne +1 influence.",
        "role": "Croissance mobile",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Base réduite de 3 à 2 ; croissance permanente ; 2 exemplaires.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-16",
        "name": "Élu des Géants",
        "status": "Deck",
        "type": "Unité",
        "subtype": null,
        "influence": 2,
        "domainCost": 3,
        "locationCost": 4,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Tant qu’un Géant est présent sur ce lieu, cette carte gagne +2 influence.",
        "role": "Soutien conditionnel",
        "complexity": "Faible",
        "risk": "Faible",
        "adjustment": "Bonus conditionnel.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-17",
        "name": "Retraite Organisée",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 2,
        "quantity": 1,
        "text": "Déplacez une carte alliée vers un lieu adjacent. La prochaine fois qu’elle devrait être détruite avant la prochaine Aube, placez-la dans votre domaine, épuisée, à la place.",
        "role": "Protection mobile",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Fenêtre et épuisement précisés.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-18",
        "name": "Feux des Ancêtres",
        "status": "Deck",
        "type": "Attachement de lieu",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 3,
        "quantity": 1,
        "text": "À l’Aube, vous pouvez déplacer une carte alliée présente sur ce lieu vers un lieu adjacent.",
        "role": "Mobilité récurrente",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Conservée.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-19",
        "name": "Migration des Clans",
        "status": "Deck",
        "type": "Éphémère",
        "subtype": null,
        "influence": null,
        "domainCost": null,
        "locationCost": null,
        "uniqueCost": 3,
        "quantity": 1,
        "text": "Déplacez jusqu’à deux cartes alliées présentes sur un même lieu vers un même lieu adjacent.",
        "role": "Déplacement de groupe",
        "complexity": "Faible",
        "risk": "Moyen",
        "adjustment": "Destination commune précisée.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      },
      {
        "faction": "Algarie",
        "id": "ALG-20",
        "name": "Chant des Steppes",
        "status": "Deck",
        "type": "Permanent — Domaine",
        "subtype": null,
        "influence": 2,
        "domainCost": 5,
        "locationCost": null,
        "uniqueCost": null,
        "quantity": 1,
        "text": "Lorsque vous remportez la Guerre, une carte alliée gagne +1 influence.",
        "role": "Croissance par Guerre",
        "complexity": "Faible",
        "risk": "Élevé",
        "adjustment": "Coût augmenté de 4 à 5.",
        "included": "Oui",
        "illustration": "assets/art/algarie.jpg"
      }
    ]
  },
  "market": [
    {
      "faction": "Marché",
      "id": "MAR-01",
      "name": "Krysta, Chercheuse Obstinée",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 2,
      "domainCost": 4,
      "locationCost": 5,
      "uniqueCost": null,
      "quantity": 1,
      "text": "À l’Aube, choisissez un :\n• Si vous ne contrôlez aucune carte nommée Shraou, créez Shraou dans votre domaine, épuisé.\n• Une carte nommée Shraou que vous contrôlez gagne +1 influence.\n• Retirez 1 influence à une carte nommée Shraou que vous contrôlez. Si vous le faites, piochez une carte.",
      "role": "Moteur compagnon",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Un seul Shraou à la fois ; coût conservé.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-02",
      "name": "Xuan Myeong, Architecte Longmai",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 2,
      "domainCost": 4,
      "locationCost": 5,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Lorsque cette carte rejoint votre domaine, si vous ne contrôlez pas de Réseau Longmai, créez-en un. Sinon, choisissez à nouveau les deux emplacements reliés par votre Réseau Longmai.",
      "role": "Mobilité structurelle",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Réseau unique ; réaffectation possible.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-03",
      "name": "Kaïros Varn, Porte-Flamme",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 2,
      "domainCost": 4,
      "locationCost": 5,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Le joueur qui contrôle ce lieu doit payer 1 or supplémentaire pour jouer ou déployer des cartes sur ce lieu.",
      "role": "Taxe au contrôleur",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Formulation au singulier et condition de contrôle précisée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-04",
      "name": "Disciple du Miroir",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 1,
      "domainCost": 2,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "La première fois chaque Jour qu’une carte adverse gagne de l’influence sur ce lieu, cette carte gagne +1 influence jusqu’à la prochaine Aube.",
      "role": "Réponse aux boosts",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Durée unifiée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-05",
      "name": "Grand Imitateur",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 2,
      "domainCost": 5,
      "locationCost": 7,
      "uniqueCost": null,
      "quantity": 1,
      "text": "À l’Aube, choisissez une autre unité présente sur ce lieu. Jusqu’à la prochaine Aube, cette carte remplace ses effets imprimés par ceux de l’unité choisie. Elle ne copie ni son nom, ni son influence, ni ses types, ni ses coûts.",
      "role": "Copie puissante",
      "complexity": "Élevée",
      "risk": "Élevé",
      "adjustment": "Coûts augmentés de 4/6 à 5/7 ; portée de la copie précisée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-06",
      "name": "Aelden, Dernier Rempart",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 3,
      "domainCost": 5,
      "locationCost": 6,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Lorsque cette carte rejoint un lieu, choisissez un mode tant qu’elle reste sur ce lieu :\n• À chaque Aube, chaque joueur détruit une carte qu’il contrôle présente sur ce lieu, s’il le peut.\n• Les cartes présentes sur ce lieu ne peuvent pas perdre d’influence.",
      "role": "Choix de règle locale",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Durée du mode et choix par joueur précisés.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-07",
      "name": "Blanche, Cantatrice des Brumes",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 2,
      "domainCost": 5,
      "locationCost": 6,
      "uniqueCost": null,
      "quantity": 1,
      "text": "À l’Aube, choisissez une autre carte présente sur ce lieu. Elle perd 1 influence jusqu’à la prochaine Aube.\nÀ la Nuit, détruisez toutes les cartes présentes sur ce lieu ayant 0 influence.",
      "role": "Exécution progressive",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Conservée ; coût élevé justifié par la menace récurrente.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-08",
      "name": "Manollo, Gardien de Rideau",
      "status": "Marché",
      "type": "Unité",
      "subtype": "Unique",
      "influence": 2,
      "domainCost": 5,
      "locationCost": 7,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Cette carte ne peut pas être déplacée.\nLorsque le lieu sur lequel elle est présente expire, elle ne compte pas dans le nombre de Survivants et reste sur le même emplacement. Elle est présente sur le lieu qui remplace le lieu expiré.",
      "role": "Présence persistante",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Influence réduite de 3 à 2 ; coûts augmentés ; persistance explicitée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-09",
      "name": "Bénédiction d’Ul",
      "status": "Marché",
      "type": "Permanent — Domaine",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 4,
      "quantity": 1,
      "text": "Vos unités ayant 1 influence imprimée ou moins gagnent +1 influence.",
      "role": "Soutien aux petites unités",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Condition basée sur l’influence imprimée pour éviter un paradoxe.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-10",
      "name": "Mue Inachevée",
      "status": "Marché",
      "type": "Attachement d’unité",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 3,
      "quantity": 1,
      "text": "Attachez cette carte à une unité présente sur un lieu.\nLes effets imprimés de la carte attachée sont ignorés. La carte attachée gagne +3 influence.",
      "role": "Transformation / silence",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Devient un Attachement permanent ; peut viser une unité adverse.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-11",
      "name": "Refuge des Fatigués",
      "status": "Marché",
      "type": "Permanent — Domaine",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 3,
      "quantity": 1,
      "text": "La première fois chaque Jour qu’une carte alliée revient dans votre domaine, gagnez 1 or dans votre réserve.",
      "role": "Récompense de retour",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Limite journalière explicite.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-12",
      "name": "Veilleuse d’Ina",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 1,
      "domainCost": 2,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "La première fois chaque Jour qu’une autre carte présente sur ce lieu devrait être détruite, vous pouvez la placer dans le domaine de son propriétaire, épuisée, à la place.",
      "role": "Sauvetage neutre",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Peut sauver allié ou adversaire ; destination et épuisement précisés.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-13",
      "name": "Chercheur de Trésor",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 1,
      "domainCost": 2,
      "locationCost": 2,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Lorsque cette carte rejoint votre domaine, gagnez 1 or dans votre réserve.",
      "role": "Économie simple",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-14",
      "name": "Collecteur d’Impôts",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 2,
      "domainCost": 3,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Au Crépuscule, si vous contrôlez le lieu sur lequel cette carte est présente, gagnez 1 or dans votre réserve.",
      "role": "Économie de contrôle",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-15",
      "name": "Archiviste Errant",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 1,
      "domainCost": 3,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "La première fois chaque Jour que cette carte rejoint un lieu, piochez une carte puis défaussez une carte.",
      "role": "Filtrage mobile",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "« Une fois par jour » corrigé et pioche pure remplacée par filtrage.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-16",
      "name": "Discours Inspirant",
      "status": "Marché",
      "type": "Éphémère",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 1,
      "quantity": 1,
      "text": "Une carte gagne +1 influence jusqu’à la prochaine Aube.",
      "role": "Boost simple",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Durée unifiée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-17",
      "name": "Sabotage",
      "status": "Marché",
      "type": "Éphémère",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 1,
      "quantity": 1,
      "text": "Une carte perd 1 influence jusqu’à la prochaine Aube.",
      "role": "Affaiblissement simple",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Durée unifiée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-18",
      "name": "Souffle des Brumes",
      "status": "Marché",
      "type": "Attachement de lieu",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 3,
      "quantity": 1,
      "text": "Les cartes jouées directement sur ce lieu arrivent avec -1 influence jusqu’à l’expiration de ce lieu. Cet effet ne concerne pas les déploiements.",
      "role": "Taxe aux cartes jouées",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Différence jouer/déployer précisée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-19",
      "name": "Seigneur de Guerre",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 4,
      "domainCost": 5,
      "locationCost": 7,
      "uniqueCost": null,
      "quantity": 1,
      "text": "À l’Aube, si cette carte possède strictement la plus haute influence parmi les cartes présentes sur ce lieu, gagnez 1 or actif.",
      "role": "Grosse unité économique",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Égalités et type d’or précisés.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-20",
      "name": "Grand Conquérant",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 3,
      "domainCost": 5,
      "locationCost": 7,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Au Crépuscule, si vous contrôlez le lieu sur lequel cette carte est présente et qu’au moins une carte adverse y est présente, cette carte gagne +1 influence.",
      "role": "Croissance par domination",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Ancien gain de 1 PV remplacé par +1 influence permanent sur lieu contesté.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-21",
      "name": "Soleil Éternel",
      "status": "Marché",
      "type": "Attachement de lieu",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 4,
      "quantity": 1,
      "text": "Les autres effets « Au Crépuscule » et « À la Nuit » des cartes présentes sur ce lieu et du lieu ne se déclenchent pas.\nCela n’empêche pas la résolution du contrôle, la vérification d’un Seuil, la diminution de la Durée ou l’expiration.",
      "role": "Neutralisation temporelle",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Exceptions structurelles précisées.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-22",
      "name": "Carnage",
      "status": "Marché",
      "type": "Attachement de lieu",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 2,
      "quantity": 1,
      "text": "Ce lieu a -1 Survivant, avec un minimum de 0.",
      "role": "Pression sur la survie",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Minimum précisé.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-23",
      "name": "Refuge Consacré",
      "status": "Marché",
      "type": "Attachement de lieu",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 2,
      "quantity": 1,
      "text": "Ce lieu a +1 Survivant.",
      "role": "Protection à l’expiration",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-24",
      "name": "Pacte de Trêve",
      "status": "Marché",
      "type": "Éphémère",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 3,
      "quantity": 1,
      "text": "Augmentez de 1 la Durée d’un lieu possédant une Durée, avec un maximum de 5.",
      "role": "Retarder une expiration",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Ne cible pas les monstres sans Durée ; plafond ajouté.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-25",
      "name": "Harponneur des Mers Froides",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 2,
      "domainCost": 2,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Tant que cette carte est présente sur un Lieu — Monstre, elle gagne +2 influence.",
      "role": "Spécialiste des monstres",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Bonus complet conservé pour contrôle, Seuil et Victoire.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-26",
      "name": "Ingénieure des Routes",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 2,
      "domainCost": 3,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Lorsque cette carte rejoint un lieu, vous pouvez payer 1 or. Si vous le faites, défaussez un Attachement de lieu présent sur ce lieu.",
      "role": "Réponse aux attachements",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-27",
      "name": "Passeuse du Val Ombré",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 1,
      "domainCost": 2,
      "locationCost": 3,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Lorsque ce lieu expire, avant de choisir les Survivants, vous pouvez détruire cette carte. Si vous le faites, une autre carte alliée présente sur ce lieu survit sans compter dans le nombre de Survivants.",
      "role": "Sauvetage sacrificiel",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Timing précisé.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-28",
      "name": "Lame Solaire de Shûmei",
      "status": "Marché",
      "type": "Attachement d’unité",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 4,
      "quantity": 1,
      "text": "La carte attachée gagne +2 influence.\nLa première fois chaque Jour qu’elle devrait perdre de l’influence, réduisez cette perte de 1.",
      "role": "Renforcement et protection",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Coût augmenté de 3 à 4.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-29",
      "name": "Recruteur de Guilde",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 1,
      "domainCost": 2,
      "locationCost": 3,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Lorsque cette carte rejoint votre domaine, vous pouvez placer une carte visible du marché sous le deck de marché. Remplacez-la immédiatement.",
      "role": "Renouvellement du marché",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-30",
      "name": "Vétéran du Rideau",
      "status": "Marché",
      "type": "Unité",
      "subtype": null,
      "influence": 2,
      "domainCost": 4,
      "locationCost": 4,
      "uniqueCost": null,
      "quantity": 1,
      "text": "Tant que cette carte est dans votre domaine, elle compte comme ayant 4 influence pour la Guerre.",
      "role": "Choix Domaine / lieu",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Coût 4/4 conservé.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-31",
      "name": "Décret de Saisie",
      "status": "Marché",
      "type": "Éphémère",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 2,
      "quantity": 1,
      "text": "Choisissez un Permanent ou un Attachement. Ses effets sont ignorés jusqu’à la prochaine Aube.",
      "role": "Réponse temporaire",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Durée unifiée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-J01",
      "name": "Aiguille de Translation",
      "status": "Marché — Module Jadis",
      "type": "Artefact de Jadis — Éphémère",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 4,
      "quantity": 1,
      "text": "Déplacez une carte présente sur un lieu vers n’importe quel autre lieu.",
      "role": "Artefact de mobilité",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Ajout pour rendre les Ruines des Hommes de Jadis fonctionnelles.",
      "included": "Optionnel",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-J02",
      "name": "Lentille des Possibles",
      "status": "Marché — Module Jadis",
      "type": "Artefact de Jadis — Éphémère",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 4,
      "quantity": 1,
      "text": "Regardez les trois premières cartes du deck de marché. Ajoutez-en une à votre main et placez les autres sous le deck dans l’ordre de votre choix.",
      "role": "Artefact de sélection",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Ajout pour le module Jadis.",
      "included": "Optionnel",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Marché",
      "id": "MAR-J03",
      "name": "Sceau d’Ancrage",
      "status": "Marché — Module Jadis",
      "type": "Artefact de Jadis — Attachement d’unité",
      "subtype": null,
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": 4,
      "quantity": 1,
      "text": "La carte attachée gagne +1 influence et ne peut pas être déplacée ou détruite par des effets de cartes.",
      "role": "Artefact défensif",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Ajout pour le module Jadis ; l’expiration peut toujours la détruire.",
      "included": "Optionnel",
      "illustration": "assets/art/neutral.jpg"
    }
  ],
  "specials": [
    {
      "faction": "Spéciale",
      "id": "SPE-01",
      "name": "Shraou",
      "status": "Créée",
      "type": "Unité recto-verso",
      "subtype": "Compagnon",
      "influence": 1,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "Lorsque cette carte rejoint un lieu, regardez la première carte du deck de lieux.\nDès que cette carte possède 5 influence ou plus, retournez-la sur sa face Shraou Muté. Elle conserve ses Attachements.",
      "role": "Compagnon de Krysta",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Transformation immédiate et conservation des Attachements précisées.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-01B",
      "name": "Shraou Muté",
      "status": "Verso",
      "type": "Unité recto-verso",
      "subtype": "Compagnon",
      "influence": 5,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "À la Nuit, les cartes adverses présentes sur ce lieu perdent 1 influence jusqu’à la prochaine Aube.",
      "role": "Forme mutée",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Verso de Shraou.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-02",
      "name": "Réseau Longmai",
      "status": "Créée",
      "type": "Permanent",
      "subtype": "Réseau",
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "Placez un marqueur Réseau sur deux emplacements de lieu. Lorsqu’un lieu marqué est remplacé, son marqueur reste sur le même emplacement.\nÀ l’Aube, vous pouvez déplacer une carte alliée d’un emplacement marqué vers l’autre.",
      "role": "Réseau de Xuan",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Le réseau relie des emplacements et non des cartes de lieu précises.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-03",
      "name": "Créature Oubliée",
      "status": "Créée",
      "type": "Unité",
      "subtype": "Jeton",
      "influence": 1,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "Cette carte ne compte pas dans le nombre de Survivants.",
      "role": "Jeton de la Montagne des Oubliés",
      "complexity": "Faible",
      "risk": "Faible",
      "adjustment": "Jeton de lieu.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-04",
      "name": "Écaille Rouge",
      "status": "Récompense",
      "type": "Attachement d’unité",
      "subtype": "Trophée",
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "La carte attachée gagne +2 influence.",
      "role": "Trophée offensif",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-05",
      "name": "Écaille Bleue",
      "status": "Récompense",
      "type": "Attachement d’unité",
      "subtype": "Trophée",
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "La carte attachée gagne +1 influence. Déployer la carte attachée depuis votre domaine coûte toujours 0 or, même si ce n’est pas votre premier déploiement du Jour.",
      "role": "Trophée de mobilité",
      "complexity": "Faible",
      "risk": "Moyen",
      "adjustment": "Vocabulaire unifié.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-06",
      "name": "Écaille Violette",
      "status": "Récompense",
      "type": "Attachement d’unité",
      "subtype": "Trophée",
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "La carte attachée gagne +1 influence. Lorsqu’un lieu sur lequel elle est présente expire, la carte alliée avec le moins d’influence sur ce lieu survit sans compter dans le nombre de Survivants. En cas d’égalité, vous choisissez.",
      "role": "Trophée de survie",
      "complexity": "Moyenne",
      "risk": "Moyen",
      "adjustment": "Conservée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-07",
      "name": "Poulpe-Navire Enchaîné",
      "status": "Récompense",
      "type": "Attachement de lieu",
      "subtype": "Monstre dompté",
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "Tant que cette carte est dans votre domaine et n’est attachée à aucun lieu, votre total d’influence pour la Guerre est réduit de 1.\nÀ l’Aube, vous pouvez payer 1 or pour attacher cette carte à un lieu non-Monstre ne contenant aucune unité.\nLe lieu attaché a -1 Survivant, minimum 0.\nAu Crépuscule, avant la résolution du contrôle, si vous ne contrôlez pas le lieu attaché, choisissez une carte adverse présente sur ce lieu. Elle perd 1 influence jusqu’à la prochaine Aube.\nLorsque le lieu attaché expire, remettez cette carte dans votre domaine.",
      "role": "Récompense risquée",
      "complexity": "Élevée",
      "risk": "Élevé",
      "adjustment": "Malus uniquement lorsqu’il est non attaché ; perte d’influence temporaire.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-08",
      "name": "Mutation d’Ul",
      "status": "Récompense",
      "type": "Attachement d’unité",
      "subtype": "Mutation",
      "influence": null,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "Attachez cette carte à une carte alliée présente sur le Berceau des Formes.\nLa carte attachée gagne +2 influence.\nLorsqu’elle devrait être détruite, vous pouvez lui retirer 1 influence à la place. Vous ne pouvez pas choisir cet effet si elle a 0 influence.",
      "role": "Mutation défensive",
      "complexity": "Moyenne",
      "risk": "Élevé",
      "adjustment": "Condition à 0 influence précisée.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Spéciale",
      "id": "SPE-09",
      "name": "Cœur des Sources Bouillantes",
      "status": "Récompense",
      "type": "Trophée — Domaine",
      "subtype": null,
      "influence": 0,
      "domainCost": null,
      "locationCost": null,
      "uniqueCost": null,
      "quantity": 0,
      "text": "Une fois par Jour, lorsque vous devriez résoudre l’effet de contrôle d’un lieu, vous pouvez retirer 1 influence à une carte alliée présente sur ce lieu. Si vous le faites, résolvez cet effet de contrôle une fois supplémentaire.",
      "role": "Trophée de contrôle",
      "complexity": "Faible",
      "risk": "Élevé",
      "adjustment": "Influence fixée à 0 pour ne pas renforcer gratuitement la Guerre.",
      "included": "Oui",
      "illustration": "assets/art/neutral.jpg"
    }
  ],
  "locations": [
    {
      "faction": "Lieu",
      "id": "LIE-01",
      "name": "Plaine des Survivants",
      "type": "Lieu",
      "subtype": null,
      "survivors": 3,
      "duration": 4,
      "vp": "5 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Le coût de lieu des cartes jouées directement sur ce lieu est réduit de 1, minimum 1.",
      "control": "Gagnez 1 or dans votre réserve.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Économie et faible coût",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-02",
      "name": "Domaine de Haute-Voûte",
      "type": "Lieu",
      "subtype": null,
      "survivors": 1,
      "duration": 3,
      "vp": "6 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "À la Nuit, la carte ayant la plus faible influence sur ce lieu perd 1 influence. En cas d’égalité, le contrôleur du lieu choisit parmi les cartes à égalité. Si personne ne contrôle le lieu, aucune carte ne perd d’influence.",
      "control": "Piochez une carte.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Pioche puissante contre danger",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-03",
      "name": "Défilé des Pèlerins",
      "type": "Lieu",
      "subtype": null,
      "survivors": 1,
      "duration": 3,
      "vp": "5 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Chaque joueur ne peut jouer ou déployer qu’une seule carte sur ce lieu chaque Jour.",
      "control": "Une carte alliée présente sur ce lieu gagne +1 influence.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Progression lente",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-04",
      "name": "Arène des Cendres",
      "type": "Lieu",
      "subtype": null,
      "survivors": 0,
      "duration": 2,
      "vp": "4 / 0 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Chaque joueur ne peut avoir qu’une seule unité présente sur ce lieu.",
      "control": "Votre unité présente sur ce lieu gagne +1 influence.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Duel de champions",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-05",
      "name": "Refuge d’Inna",
      "type": "Lieu",
      "subtype": null,
      "survivors": 3,
      "duration": 4,
      "vp": "4 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Les cartes ayant 2 influence imprimée ou moins présentes sur ce lieu gagnent +1 influence et ne peuvent pas être détruites par des effets de cartes.",
      "control": "Remettez dans votre main une carte alliée ayant 1 influence imprimée ou moins depuis votre défausse.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Protection des faibles",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-06",
      "name": "Montagne des Oubliés",
      "type": "Lieu",
      "subtype": null,
      "survivors": 2,
      "duration": 3,
      "vp": "5 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Les cartes ayant exactement 1 influence comptent comme ayant 3 influence sur ce lieu.",
      "control": "Si vous ne contrôlez pas déjà de Créature Oubliée sur ce lieu, créez-en une sur ce lieu.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Valorisation des petites cartes",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-07",
      "name": "Bastion Scellé",
      "type": "Lieu",
      "subtype": null,
      "survivors": 2,
      "duration": 3,
      "vp": "5 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Les joueurs ne peuvent pas déployer de cartes depuis leur domaine sur ce lieu.",
      "control": "Choisissez une carte alliée présente sur ce lieu. Si ce lieu expire cette Nuit, cette carte survit sans compter dans le nombre de Survivants.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Jeu direct depuis la main",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-08",
      "name": "Ruines des Hommes de Jadis",
      "type": "Lieu",
      "subtype": "Module Jadis",
      "survivors": 1,
      "duration": 3,
      "vp": "6 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Les Artefacts de Jadis sont mélangés au deck de marché.",
      "control": "Regardez la première carte du deck de marché. Vous pouvez la laisser au-dessus du deck ou la placer sous le deck.",
      "victory": "1er : 6 PV. Révélez les cartes du deck de marché jusqu’à révéler un Artefact de Jadis. Jouez immédiatement cet Artefact gratuitement. Placez les autres cartes révélées sous le deck de marché dans un ordre aléatoire.\nLes autres joueurs gagnent les PV normaux.",
      "copies": 1,
      "included": "Optionnel",
      "role": "Nécessite les 3 Artefacts de Jadis",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-10",
      "name": "Le Faux-Navire Fulgurant",
      "type": "Lieu — Monstre",
      "subtype": null,
      "survivors": 1,
      "duration": "Aucune",
      "vp": "5 / 2 / 0",
      "threshold": "5 × nombre de joueurs",
      "quantity": 1,
      "effect": "Les cartes présentes sur ce lieu ne peuvent pas être déplacées par leur contrôleur.\nÀ la Nuit, si l’influence totale atteint le Seuil, le monstre est vaincu et le lieu expire.",
      "control": "Vous pouvez retirer 1 influence à une carte alliée présente sur ce lieu. Si vous le faites, gagnez 1 or dans votre réserve.",
      "victory": "1er : 5 PV, puis choisissez : gagner 4 ors dans votre réserve ou gagner Poulpe-Navire Enchaîné. Chaque autre joueur ayant au moins 3 influence gagne 2 PV.",
      "copies": 1,
      "included": "Oui",
      "role": "Monstre-piège",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-11",
      "name": "Berceau des Formes",
      "type": "Lieu — Monstre",
      "subtype": "Créature d’Ul",
      "survivors": 1,
      "duration": "Aucune",
      "vp": "4 / 2 / 0",
      "threshold": "5 × nombre de joueurs",
      "quantity": 1,
      "effect": "Sur ce lieu, les gains et pertes d’influence provoqués par des effets sont augmentés de 1. Ils gardent leur durée normale. Cet effet ne s’applique qu’aux cartes présentes sur ce lieu et ne s’applique pas aux récompenses de Victoire.\nÀ la Nuit, si l’influence totale atteint le Seuil, le monstre est vaincu et le lieu expire.",
      "control": "Vous pouvez retirer 1 influence à une carte alliée présente sur ce lieu. Si vous le faites, une autre carte alliée présente sur ce lieu gagne +1 influence.",
      "victory": "1er : 4 PV et gagnez Mutation d’Ul. Chaque autre joueur ayant au moins 3 influence gagne 2 PV.",
      "copies": 1,
      "included": "Oui",
      "role": "Amplifie aussi son propre effet de contrôle",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-12",
      "name": "Dragon des Sources Bouillantes",
      "type": "Lieu — Monstre",
      "subtype": "Dragon",
      "survivors": 1,
      "duration": "Aucune",
      "vp": "6 / 3 / 0",
      "threshold": "7 × nombre de joueurs",
      "quantity": 1,
      "effect": "Tant que ce lieu est actif, les joueurs qui ne le contrôlent pas doivent retirer 1 influence à une carte alliée présente sur un lieu pour résoudre l’effet de contrôle de ce lieu. S’ils ne le font pas, ils ne résolvent pas cet effet de contrôle.\nÀ la Nuit, si l’influence totale atteint le Seuil, le monstre est vaincu et le lieu expire.",
      "control": "Vous ignorez l’effet global de ce lieu.",
      "victory": "1er : 6 PV et gagnez Cœur des Sources Bouillantes. Chaque autre joueur ayant au moins 4 influence gagne 3 PV.",
      "copies": 1,
      "included": "Oui",
      "role": "Menace globale",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-13",
      "name": "Grande Route de Cirelion",
      "type": "Lieu",
      "subtype": null,
      "survivors": 1,
      "duration": 3,
      "vp": "5 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Lorsque ce lieu expire, avant de choisir les Survivants, chaque joueur peut déplacer 1 carte alliée présente sur ce lieu vers un lieu adjacent. Les cartes déplacées ainsi ne comptent pas comme Survivantes.",
      "control": "Déplacez une carte alliée présente sur ce lieu vers un lieu adjacent, ou déplacez une carte alliée présente sur un lieu adjacent vers ce lieu.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Mobilité locale",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-14",
      "name": "Mines du Rideau",
      "type": "Lieu",
      "subtype": null,
      "survivors": 1,
      "duration": 3,
      "vp": "5 / 2 / 0",
      "threshold": null,
      "quantity": 1,
      "effect": "Pour chaque joueur, la première fois chaque Jour qu’une carte qu’il contrôle rejoint ce lieu, il gagne 1 or dans sa réserve.",
      "control": "Gagnez 1 or dans votre réserve.",
      "victory": "Attribuez les PV selon le classement normal.",
      "copies": 1,
      "included": "Oui",
      "role": "Économie risquée",
      "illustration": "assets/art/neutral.jpg"
    },
    {
      "faction": "Lieu",
      "id": "LIE-15",
      "name": "Bois des Deux Couronnes",
      "type": "Lieu",
      "subtype": null,
      "survivors": 2,
      "duration": 3,
      "vp": "Spécial",
      "threshold": null,
      "quantity": 1,
      "effect": "Ce lieu possède deux Couronnes. Le contrôle du lieu est déterminé normalement par l’influence totale.",
      "control": "Une carte alliée présente sur ce lieu gagne +1 influence.",
      "victory": "Couronne Mimbraïque — Le joueur contrôlant la carte ayant la plus haute influence sur ce lieu gagne 3 PV.\nCouronne Asturienne — Le joueur ayant le plus de cartes sur ce lieu gagne 3 PV.\nSi un même joueur gagne les deux Couronnes, il gagne 5 PV au lieu de 6. En cas d’égalité pour une Couronne, personne ne la gagne.",
      "copies": 1,
      "included": "Oui",
      "role": "Trois axes : contrôle total, plus grosse carte, nombre de cartes",
      "illustration": "assets/art/neutral.jpg"
    }
  ]
};
